module.exports = {
  "en-US": {
    "AND": " and",
    "NO_RESULTS_FOUND": "{0} did not return any results on YouTube.",
    "NO_VIDEO_QUERY_DEFINED": "Please describe in your request which titles you would like to play.",
    "NO_PLIST_QUERY_DEFINED": "Please describe in your request which Playlist you would like to play.",
    "NO_PLIST_FOUND": "No Playlist found.",
    "NOW_PLAYING": "I am now playing {0}.",
    "ADD_TO_PLAYLIST": "Song has been added to the PlayList {0}.",
    "ALREADY_IN_PLAYLIST": "Song has already been added to PlayList {0}.",
    "REMOVE_FROM_PLAYLIST": "Song was removed from the PlayList.",
    "PLAYLIST_REMOVED": "PlayList {0} has been removed.",
    "ALL_PLAYLISTS_REMOVED": "All PlayLists have been removed.",
    "GET_ALL_PLAYLISTS": "The following playlists were found: {0}.",
    "ONLY_NUMBER_PLIST_QUERY": "Only numbers are allowed as playlist names.",
    "NOT_IN_PLAYLIST": "Song was not found in the PlayList.",
    "NOTHING_TO_RESUME": "You are not playing anything currently.",
    "NOTHING_TO_REPEAT": "You have not selected a video to play.",
    "LOOP_ON_TRIGGERED": "I will repeat your {0} selection infinitely.",
    "LOOP_OFF_TRIGGERED": "I will no longer repeat your {0} selection.",
    "REPEAT_TRIGGERED": "I will repeat your {0} selection once.",
    "HELP_TRIGGERED": "To use the YouTube skill, tell the skill to search for the video you want. Additionally, once the video is playing, you can tell Alexa to  pause, restart, or loop it."
  },
  "de-DE": {
    "AND": " und",
    "NO_RESULTS_FOUND": "Keine Ergebnisse auf Youtube gefunden.",
    "NO_VIDEO_QUERY_DEFINED": "Bitte nennen Sie in Ihrer Anfrage, welche Titel Sie hören möchten.",
    "NO_PLIST_QUERY_DEFINED": "Bitte nennen Sie in Ihrer Anfrage, welche Playlist Sie abspielen möchten.",
    "NO_PLIST_FOUND": "Keine Playlist gefunden.",
    "NOW_PLAYING": "Ich spiele jetzt {0}.",
    "ADD_TO_PLAYLIST": "Lied wurde in der PlayList {0} eingefügt.",
    "ALREADY_IN_PLAYLIST": "Lied wurde bereits in der PlayList {0} eingefügt.",
    "REMOVE_FROM_PLAYLIST": "Lied wurde von der PlayList entfernt.",
    "PLAYLIST_REMOVED": "PlayList {0} wurde entfernt.",
    "ALL_PLAYLISTS_REMOVED": "Alle PlayLists wurde entfernt.",
    "GET_ALL_PLAYLISTS": "Die folgende PlayLists wurde gefunden: {0}.",
    "ONLY_NUMBER_PLIST_QUERY": "Nur Nummer sind als Playlist Namen erlaubt.",
    "NOT_IN_PLAYLIST": "Lied wurde nicht in der PlayList gefunden.",
    "NOTHING_TO_RESUME": "Sie spielen derzeit nichts.",
    "NOTHING_TO_REPEAT": "Sie haben kein Video zum Abspielen ausgewählt.",
    "LOOP_ON_TRIGGERED": "Ich werde deine Auswahl unendlich wiederholen.",
    "LOOP_OFF_TRIGGERED": "Ich werde deine Auswahl nicht mehr wiederholen.",
    "REPEAT_TRIGGERED": "Ich werde deine Auswahl einmal wiederholen.",
    "HELP_TRIGGERED": "Um die YouTube-Fertigkeit zu verwenden, musst du die Fähigkeit angeben, nach dem gewünschten Video zu suchen. Wenn das Video abgespielt wird, können Sie Alexa außerdem mitteilen, dass es angehalten, neu gestartet oder wiederholt werden soll."
  },
  "fr-FR": {
    "AND": " et",
    "NO_RESULTS_FOUND": "Aucun résultat trouvé sur Youtube",
    "NO_VIDEO_QUERY_DEFINED": "Veuillez indiquer dans votre demande quels titres vous souhaitez entendre.",
    "NO_PLIST_QUERY_DEFINED": "Veuillez indiquer dans votre demande quelle liste de lecture vous souhaitez lire.",
    "NO_PLIST_FOUND": "Aucune playlist trouvée.",
    "NOW_PLAYING": "Je suis en train de jouer {0}.",
    "ADD_TO_PLAYLIST": "La chanson a été insérée dans la liste de lecture {0}.",
    "ALREADY_IN_PLAYLIST": "La chanson a déjà été ajoutée à la liste de lecture {0}.",
    "REMOVE_FROM_PLAYLIST": "La chanson a été retirée de la liste de lecture.",
    "PLAYLIST_REMOVED": "La liste de lecture {0} a été supprimée.",
    "ALL_PLAYLISTS_REMOVED": "Toutes les listes de lecture ont été supprimées.",
    "GET_ALL_PLAYLISTS": "Les listes de lecture suivantes ont été trouvées: {0}.",
    "ONLY_NUMBER_PLIST_QUERY": "Seuls les nombres sont autorisés comme noms de listes de lecture.",
    "NOT_IN_PLAYLIST": "La chanson n’a pas été trouvée dans la liste de lecture.",
    "NOTHING_TO_RESUME": "Il n'y a aucun élément en cours de lecture.",
    "NOTHING_TO_REPEAT": "Vous n'avez pas sélectionné de vidéo à écouter.",
    "LOOP_ON_TRIGGERED": "Je vais répéter votre sélection à l'infini.",
    "LOOP_OFF_TRIGGERED": "Je ne vais pas répéter votre sélection.",
    "REPEAT_TRIGGERED": "Je vais répéter votre sélection une fois.",
    "HELP_TRIGGERED": "Pour utiliser cette skill, dites à Alexa de rechercher la vidéo que vous souhaitez. De plus, lorsque la lecture est en cours, vous pouvez dire à Alexa de mettre en pause, redémarrer, ou répéter."
  },

  "it-IT": {
    "AND": "e",
    "NO_RESULTS_FOUND": "Non ho trovato nessun risultato per {0}.",
    "NO_VIDEO_QUERY_DEFINED": "Per favore, dimmi nella tua richiesta quale brano vorresti riprodurre.",
    "NO_PLIST_QUERY_DEFINED": "Per favore, dimmi nella tua richiesta quale playlist vorresti riprodurre.",
    "NO_PLIST_FOUND": "Non ho trovato nessuna playlist per {0}.",
    "NOW_PLAYING": "Sto riproducendo {0}.",
    "ADD_TO_PLAYLIST": "La canzone è stata aggiunta alla lista {0}.",
    "ALREADY_IN_PLAYLIST": "La canzone è già nella lista {0}.",
    "REMOVE_FROM_PLAYLIST": "La canzone è stata rimossa dalla lista",
    "PLAYLIST_REMOVED": "La playlist {0} è stata rimossa.",
    "ALL_PLAYLISTS_REMOVED": "Tutte le playlist sono state rimosse.",
    "GET_ALL_PLAYLISTS": "Sono state trovate queste playlist: {0}.",
    "ONLY_NUMBER_PLIST_QUERY": "Sono disponibili solamente numeri come nomi delle playlist.",
    "NOT_IN_PLAYLIST": "La canzone non è stata trovata nella playlist.",
    "NOTHING_TO_RESUME": "Al momento non stai riproducendo niente.",
    "NOTHING_TO_REPEAT": "Non hai selezionato alcun video da riprodurre.",
    "LOOP_ON_TRIGGERED": "Ripeterò il brano {0} per quanto lo vorrai.",
    "LOOP_OFF_TRIGGERED": "Non ripeterò più il brano {0}",
    "REPEAT_TRIGGERED": "Ripeterò il brano {0} una volta sola.",
    "HELP_TRIGGERED": "Per usare la skill di Youtube, dì alla skill di cercare il video che vuoi. In più, una volta che il video è in riproduzione, puoi dire ad Alexa di metterlo in pausa, farlo ripartire, o metterlo in loop."
  }
};